### ISSUE TITLE
CMake executable name conflict with MAPL_Profiler demo.x

### ISSUE THREAD

**Issue by lizziel** [Goddard-Fortran-Ecosystem/gFTL-shared#22]
There is a name conflict for executable demo.x If building gFTL-shared within the source same tree as MAPL, as is done for [GCHPctm](https://github.com/geoschem/gchpctm). 

```
CMake Error at src/MAPL/MAPL_Profiler/demo/CMakeLists.txt:1 (add_executable):
  add_executable cannot create target "demo.x" because another target with
  the same name already exists.  The existing target is an executable created
  in source directory
  "/n/home08/elundgren/GC/Code.GCHPctm/src/gFTL-shared/src".  See
  documentation for policy CMP0002 for more details.
```

This can be resolved by renaming one of the executables to a different name.

**Comment by tclune** [comment]
Ugh.   This feels like cmake "chicken".    I guess GEOS is immune because gFTL-shared is installed separately.   

You could push a PR that renames the MAPL one to be MAPL.profiler.demo.x
Will gladly approve it.

**Comment by lizziel** [comment]
Okay, great. I wasn't sure which one you'd prefer to be renamed. For now I had just not added the subdirectory for MAPL_Profiler.

**Comment by tclune** [comment]
Ultimately it should be both, but MAPL is rolling out a new version anyway.    And gFTL releases can be a pain to propagate - though in this case I would not need to update the other GFE repos.
