### ISSUE TITLE
why the StringSetIterator is missing ?

### ISSUE THREAD

**Issue by weiyuan-jiang** [Goddard-Fortran-Ecosystem/gFTL-shared#64]
The type StringSet is defined, but why its iterator is missing ?

**Comment by tclune** [comment]
@weiyuan-jiang could you provide more details?   The gFTL template definitely has `begin()`, `end()`, `ftn_begin()` and `ftr_end()` methods to create an iterator from Set.   Perhaps provide a non-working example that you expect should work (or at least compile)?

**Comment by weiyuan-jiang** [comment]
type(StringSetIterator) would not compile. That means the type is not defined. I checked the library, there is no stringsetitertor either.

**Comment by tclune** [comment]
Please provide a minimal reproducer.    I'm fairly certain that I have unit tests that cover this, so I think the problem is something else.

**Comment by tclune** [comment]
Looking at one of my builds, it does look like it gets called `SetIterator` instead of `StringSetIterator`.  Having trouble looking into it at the moment though, as I have a new laptop and am still getting the compilers installed.

**Comment by tclune** [comment]
Yup - something is wrong with the template and the iterator is getting the generic name instead of the type-specific name.   Can use `SetIterator` for now, and I'll work on a hotfix.

**Comment by tclune** [comment]
The proper fix is a bit subtle.    gFTL-shared mixes Set containers in with Deque, Queue, and Stack.   The last 2 do not have iterators.  Deque does.    I need to create a new subdirectory and put Deque and Set there ...
