### ISSUE TITLE
Build with Fujitsu Compiler

### ISSUE THREAD

**Issue by wkensuke** [Goddard-Fortran-Ecosystem/gFTL-shared#71]
I use Spack to evaluate Fujitsu Compiler for Fugaku and FX1000.
When I tried to build this package(v1.7.0), I received an error similar to the following:
```
==> Error: ProcessError: Command exited with status 1:
    '/fefs/spack2/spack/opt/spack/linux-rhel8-a64fx/fj-4.10.0/cmake-3.27.4-o4w4ad5gemgpf5teeimtmxl3mpktqzom/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/fefs/spack2/spack/opt/spack/linux-rhel8-a64fx/fj-4.10.0/gftl-shared-1.7.0-t4vfydc53scqqqketa5uiqwefcfkezkh' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/fefs/spack2/spack/opt/spack/linux-rhel8-a64fx/fj-4.10.0/gftl-shared-1.7.0-t4vfydc53scqqqketa5uiqwefcfkezkh/lib;/fefs/spack2/spack/opt/spack/linux-rhel8-a64fx/fj-4.10.0/gftl-shared-1.7.0-t4vfydc53scqqqketa5uiqwefcfkezkh/lib64' '-DCMAKE_PREFIX_PATH:STRING=/fefs/spack2/spack/opt/spack/linux-rhel8-a64fx/fj-4.10.0/gftl-1.11.0-rqedzzjschqifkbb3rvn3spanukrbagq;/fefs/spack2/spack/opt/spack/linux-rhel8-a64fx/fj-4.10.0/cmake-3.27.4-o4w4ad5gemgpf5teeimtmxl3mpktqzom' '/fefs/spack2/tmp/spack-stage/spack-stage-gftl-shared-1.7.0-t4vfydc53scqqqketa5uiqwefcfkezkh/spack-src'

1 error found in build log:
     9     
     10    
     11    -- The Fortran compiler identification is Fujitsu 4.10.0
     12    -- Detecting Fortran compiler ABI info
     13    -- Detecting Fortran compiler ABI info - done
     14    -- Check for working Fortran compiler: /fefs/spack2/spack/lib/spack/env/fj/frt - skipped
  >> 15    CMake Error at CMakeLists.txt:35 (include):
     16      include could not find requested file:
     17    
     18        Fujitsu
     19    
     20    
     21    -- Performing Test _LOGICAL_DEFAULT_KIND: SUCCESS (value=4)
```

I think it is because there is no `Fujitsu.cmake` in [cmake](https://github.com/Goddard-Fortran-Ecosystem/gFTL-shared/tree/main/cmake) directory.
Can you add the file to the cmake directory if I suggest the necessary options?
If it's not easy, I will post a patch to Spack.

**Comment by tclune** [comment]
If you specify the options, we can add the appropriate cmake file.    Note that we will have no means to test the file.

**Comment by mathomp4** [comment]
@wkensuke Indeed. If you can supply a `Fujitsu.cmake` I can work on getting the file into all the GFE repos. We can work on releases and I can get them to spack.

Also, do you know if there is a version of frt that we should target? A la:

```
if (CMAKE_Fortran_COMPILER_VERSION VERSION_LESS 8.0)
  message(FATAL_ERROR "${CMAKE_Fortran_COMPILER_ID} version must be at least 8.0!")
endif ()
```
and that I could add as a conflict in the spack packages as well.

**Comment by wkensuke** [comment]
Thank you for your replies.

> Note that we will have no means to test the file.

Yes, I understand. After adding the file, I will check the release and let you know if there are any problems.

>Also, do you know if there is a version of frt that we should target? A la:

After confirming the internal procedures, I will contact you about the details together with the above.

**Comment by wkensuke** [comment]
Hi

Could you create a fujitsu.cmake file with the following settings?
```
# Compiler specific flags for Fujitsu Fortran compiler

set(check_all "-Nquickdbg")
set(cpp "-Cfpp")

set(CMAKE_Fortran_FLAGS_DEBUG"-O0 ${check_all}") 
set(CMAKE_Fortran_FLAGS_RELEASE "-O3") 
set(CMAKE_Fortran_FLAGS "-g ${cpp} -Nalloc_assign -Free")
```

> Also, do you know if there is a version of frt that we should target? A la:

The compiler version check is as follows:
```
  if (CMAKE_Fortran_COMPILER_ID MATCHES Fujitsu)
     if (CMAKE_Fortran_COMPILER_VERSION VERSION_LESS 4.10.0)
        message(FATAL_ERROR "${CMAKE_Fortran_COMPILER_ID} version must be at least 4.10.0!")
     endif ()
  endif ()
```

The above settings have been verified locally.

**Comment by mathomp4** [comment]
@wkensuke Okay. The PRs are in as you can see from the above 6 PRs. @tclune is at the Fortran Standards meeting this week, so getting out releases might take a bit longer than usual (might be next week), but we'll get on them when we can.

**Comment by wkensuke** [comment]
@mathomp4 Thank you for creating PRs.
It’s okay, I’m not in a hurry.

**Comment by mathomp4** [comment]
@wkensuke I have a PR in spack to update the versions:

https://github.com/spack/spack/pull/43082

Hopefully I got the Fujitsu parts right :)

**Comment by wkensuke** [comment]
@mathomp4 @tclune 
I appreciate your cooperation! Also, thank you for the pull requests to spack.
I'll find time to try it👍
